### ISSUE TITLE
Update Base Finding

### ISSUE THREAD

**Issue by NickHMetzler** [NickHMetzler/Air-Bot#2]
- [x] For regular maps create a text file with the base locations and which index they are
- [x] For EC maps, call the base finding function to track the x location
- [x] Store the x location in a global variable after first found, then use that to search for the base
- This removes issues if someone else bombs a base first

**Comment by NickHMetzler** [comment]
Already Solved using JSON

**Comment by ImXenonn** [comment]
How can I get the required assets to run the AFK Bot like it says in your posting?

**Comment by NickHMetzler** [comment]
> How can I get the required assets to run the AFK Bot like it says in your posting?

Hi @ImXenonn, I am currently working on getting the production version of this out, should be within a week or two

**Comment by ImXenonn** [comment]
Awesome, It would be great if you could DM me on discord ( imxenonn ) when everything is functional. I'm looking forward to using the bot and as long as there's 0 risk of ban I would be happy to donate.

**Comment by ImXenonn** [comment]
Sorry I declined your friend request on accident, I sent you a friend request back tho whenever you get the chance to check discord :D
