### ISSUE TITLE
The Air bot.py

### ISSUE THREAD

**Issue by Scooper263** [NickHMetzler/Air-Bot#5]
I have recently discovered bots in my 8 years of playing war thunder and want to try your bot out i downloaded the files and extracted them to a folder and it seems the steps dont line up with my screen I cannot launch the "Air_Bot.py" due to the fact it is not an application and only a blank white file get back to me i am very interested.

**Comment by Scooper263** [comment]
i see that it is a py file i have never dealt with such in my life could i have some assistance with the whole operation?

**Comment by NickHMetzler** [comment]
Hi there. This repository will not work at the moment since you will need the environment variables and decryption key.

I am building a full release exe

**Comment by Scooper263** [comment]
Ahh okay so I’m assuming it will be out for a while? That is fine I am thrilled to pilot this experiment.

**Comment by NickHMetzler** [comment]
@Scooper263 at the moment it works pretty much flawlessly on 21:9 aspect ratio since that is my native screen size. I need to test it with 16:9 and possibly get new assets for that aspect ratio

**Comment by Scooper263** [comment]
alright gotcha I am looking forward to this!

**Comment by Scooper263** [comment]
Hey nick do you have a discord/server dedicated to this project for updates and stuff or no?

**Comment by NickHMetzler** [comment]
@Scooper263 add me on discord "surfshack"
