### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by zaixia108** [NickHMetzler/Air-Bot#7]
I do not understand what is the point of doing this, you have released the source code, now require the user needs to use your exe and what is the point of it

**Comment by zaixia108** [comment]
All I can say is that if you need to make some money then upload only the exe, your source code is here and asking users to use the exe doesn't seem to make much sense

**Comment by NickHMetzler** [comment]
Hi @zaixia108. I'm not fully done production as I am working some bugs out. This page is for contributors and my portfolio.
